# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiNoiseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
