# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PiNoiseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=45)),
                ('reply', models.CharField(max_length=1000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PiNoiseApp.Posts')),
            ],
        ),
    ]
