# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiNoiseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='pic',
            field=models.ImageField(blank=True, upload_to='post_pic'),
        ),
    ]
