# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiNoiseApp', '0002_auto_20170820_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
