# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiNoiseApp', '0002_users_governmententity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='governmentEntity',
            field=models.IntegerField(blank=True),
        ),
    ]
