# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiNoiseApp', '0003_auto_20170906_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='governmentEntity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
